# Generated by Django 2.2 on 2021-04-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Image',
            new_name='ques_image',
        ),
    ]
